server:
  port: 8006
spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #homename:127.0.0.1
        service-name: ${spring.application.name} #cloud-payment-service
