server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumenr
  rabbitmq:
    host: 192.168.74.129
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，本次为json，本文要设置为“text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: atguiguA




eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
  instance:
    instance-id: receive-8802.com
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"